package tradingbot.model;

public enum Coin {
    BTCUSDT, ETHUSDT, SOLUSDT,
    // ADAUSDT, XRPUSDT, DOGEUSDT, MATICUSDT, DOTUSDT, AVAXUSDT, SHIBUSDT, LTCUSDT, ATOMUSDT,
    // LINKUSDT, TRXUSDT, XLMUSDT, UNIUSDT, FILUSDT, AAVEUSDT, ALGOUSDT;
}
