version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: tradingbot_postgres
    environment:
      POSTGRES_USER: tradingAdmin
      POSTGRES_PASSWORD: tradingPass
      POSTGRES_DB: tradingdb
    ports:
      - "5432:5432"
    networks:
      - trading_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "tradingdb"]
      interval: 10s
      retries: 5

  tradingbot:
    build:
      context: .
    container_name: tradingbot_app
    ports:
      - "8080:8080"
    env_file:
      - .env  # ✅ Load .env variables
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/tradingdb
      SPRING_DATASOURCE_USERNAME: tradingAdmin
      SPRING_DATASOURCE_PASSWORD: tradingPass
      LOGGING_FILE_NAME: /logs/tradingbot.log
    depends_on:
      postgres:
        condition: service_healthy  # ✅ Wait until PostgreSQL is ready
    volumes:
      - ./.env:/app/.env  # ✅ Mount .env inside container
    restart: always
    networks:
      - trading_network

  # Volumes
volumes:
  postgres_data:
  logs:

# Networks
networks:
  trading_network:
    driver: bridge